// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationADs_Eixo2.Models;

#nullable disable

namespace WebApplicationADs_Eixo2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231124220244_M004CALENDARIO_CORRECOES")]
    partial class M004CALENDARIO_CORRECOES
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCalendario")
                        .HasColumnType("int");

                    b.Property<int>("IdColaborador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCalendario")
                        .IsUnique();

                    b.HasIndex("IdColaborador");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAgendamento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAgendamento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Calendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFimEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInicioEvento")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("PedindoAjuda")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.DadosUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataNacimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeficienciaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("IdDeficiencia")
                        .HasColumnType("int");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeficienciaID");

                    b.HasIndex("IdDeficiencia");

                    b.ToTable("DadosUsuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Deficiencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Deficiencia");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("Colaborador")
                        .HasColumnType("bit");

                    b.Property<bool>("Deficiente")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Agendamento", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Calendario", "Calendario")
                        .WithOne("Agendamento")
                        .HasForeignKey("WebApplicationADs_Eixo2.Models.Agendamento", "IdCalendario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "Colaborador")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendario");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Avaliacao", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Agendamento", "Agendamento")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdAgendamento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Calendario", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "Usuario")
                        .WithMany("Calendarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.DadosUsuarios", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Deficiencia", null)
                        .WithMany("DadosUsuarios")
                        .HasForeignKey("DeficienciaID");

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "Usuario")
                        .WithOne("DadosUsuarios")
                        .HasForeignKey("WebApplicationADs_Eixo2.Models.DadosUsuarios", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationADs_Eixo2.Models.Deficiencia", "Deficiencia")
                        .WithMany()
                        .HasForeignKey("IdDeficiencia");

                    b.Navigation("Deficiencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Usuarios", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Agendamento", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Calendario", b =>
                {
                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Deficiencia", b =>
                {
                    b.Navigation("DadosUsuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Usuarios", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Calendarios");

                    b.Navigation("DadosUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
