// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationADs_Eixo2.Models;

#nullable disable

namespace WebApplicationADs_Eixo2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarioID")
                        .HasColumnType("int");

                    b.Property<int>("Colaborador")
                        .HasColumnType("int");

                    b.Property<int>("Deficiente")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCalendario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioColaboradorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioDeficienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioID");

                    b.HasIndex("UsuarioColaboradorId");

                    b.HasIndex("UsuarioDeficienteId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Amigos", b =>
                {
                    b.Property<int>("Usuario1")
                        .HasColumnType("int");

                    b.Property<int>("Usuario2")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAmizade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User1Id")
                        .HasColumnType("int");

                    b.Property<int?>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Usuario1", "Usuario2");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.AvaliacaoAgendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .HasColumnType("int");

                    b.Property<int>("Avaliador")
                        .HasColumnType("int");

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserAvaliadorId")
                        .HasColumnType("int");

                    b.HasKey("IdAgendamento", "Avaliador");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("UserAvaliadorId");

                    b.ToTable("AvaliacaoAgendamento");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Calendario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.DadosUsuarios", b =>
                {
                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataNacimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("IdDeficiencia")
                        .HasColumnType("int");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUser");

                    b.HasIndex("IdDeficiencia");

                    b.ToTable("DadosUsuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Deficiencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Deficiencia");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.MensagensPrivadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDestinatario")
                        .HasColumnType("int");

                    b.Property<int>("IdRemetente")
                        .HasColumnType("int");

                    b.Property<string>("TextoMensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioDestinatarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioRemetenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinatarioId");

                    b.HasIndex("UsuarioRemetenteId");

                    b.ToTable("MensagensPrivadas");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Notificacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDestinatario")
                        .HasColumnType("int");

                    b.Property<string>("TextoMensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("lido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdDestinatario");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Perfil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("Colaborador")
                        .HasColumnType("bit");

                    b.Property<bool>("Deficiente")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Preferencias", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Preferencias");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Agendamento", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Calendario", "Calendario")
                        .WithMany()
                        .HasForeignKey("CalendarioID");

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "UsuarioColaborador")
                        .WithMany()
                        .HasForeignKey("UsuarioColaboradorId");

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "UsuarioDeficiente")
                        .WithMany()
                        .HasForeignKey("UsuarioDeficienteId");

                    b.Navigation("Calendario");

                    b.Navigation("UsuarioColaborador");

                    b.Navigation("UsuarioDeficiente");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Amigos", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id");

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.AvaliacaoAgendamento", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId");

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "UserAvaliador")
                        .WithMany()
                        .HasForeignKey("UserAvaliadorId");

                    b.Navigation("Agendamento");

                    b.Navigation("UserAvaliador");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Calendario", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "Usuario")
                        .WithMany("AllCalendario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.DadosUsuarios", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "Usuario")
                        .WithOne("DadosUsuarios")
                        .HasForeignKey("WebApplicationADs_Eixo2.Models.DadosUsuarios", "IDUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationADs_Eixo2.Models.Deficiencia", "Deficiencia")
                        .WithMany("DadosUsuarios")
                        .HasForeignKey("IdDeficiencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deficiencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.MensagensPrivadas", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "UsuarioDestinatario")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinatarioId");

                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "UsuarioRemetente")
                        .WithMany()
                        .HasForeignKey("UsuarioRemetenteId");

                    b.Navigation("UsuarioDestinatario");

                    b.Navigation("UsuarioRemetente");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Notificacoes", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Usuarios", "UsuarioDestinatario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("IdDestinatario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioDestinatario");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Usuarios", b =>
                {
                    b.HasOne("WebApplicationADs_Eixo2.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Deficiencia", b =>
                {
                    b.Navigation("DadosUsuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebApplicationADs_Eixo2.Models.Usuarios", b =>
                {
                    b.Navigation("AllCalendario");

                    b.Navigation("DadosUsuarios");

                    b.Navigation("Notificacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
